### PR TITLE
Update import refs and deps

### PR DESCRIPTION
**Pull request by nickgsc**
Due to recent upstream changes in the source project, our own version stopped being able to build. This PR simply updates the import references to point to our own version (instead of the upstream fork), and also checks in the supporting files for using dep for managing dependencies.

### CODE REVIEW

**Review by looking-promising — CHANGES_REQUESTED** [review]
I think we should check in our vendor files for now if possible.  This is the most reliable and deterministic way to build a go application.   Checking in vendor does not preclude the use of `dep`, which seems like a good idea.  @ndwhtlssthr, what are your thoughts on this?

**Comment by nickgsc** [comment]
The vendor folder was already in the `.gitignore` so by virtue of me running the dep stuff, it removed it from the repo. I know very little about the pros/cons of any of the approaches, so I'm fine with whatever 😬

**Comment by nickgsc** [comment]
Mostly I just wanted it to be possible to pull down this repo and be able to build it (I hadn't tried to before today, and the upstream changes made it not possible)

**Comment by looking-promising** [comment]
Yep -- makes sense.  I'm sure we should have checked in vendor in the first place -- if we had, you would have been able to build it when you pulled it down (well maybe not with the wrong import statements).  Going forward, though, we could avoid that problem. :-)

**Review by nathanows — APPROVED** [review]
This project didn't use `dep` originally. Based on the `vendor.json` file segmentio was using `govendor` for this originally. I like converting it over to `dep` makes sense with our current GSC Go direction. Changing the import paths makes sense, missed it our first go-around on this. 

I don't know that I feel too strongly on whether or not to check in vendor in this case. I feel like we've been generally advising that libraries should not check-in vendor, apps should. This is kind of a mix... I guess I kind of think of our (aws-secrets app)[ https://github.com/gospotcheck/aws-secrets] as the true app (but to be fair I still use our chamber fork directly sometimes. 

It may be nice to come up with some policies for CLI apps around checking in a pre-build image so we lower the barrier to entry and verify we have a working build. In the CLI apps I've been working on I've been checking in an OSx binary in `bin/osx`. 

I'm fine with the PR though, more just discussion points for some point in the future.

**Review by looking-promising — APPROVED** [review]

**Pull request closed without merging**
